set(STEAMSCREENSHOTS_DEPENDENCY_CACHE_DIR "${PROJECT_SOURCE_DIR}/thirdparty/cache" CACHE PATH "Downloaded binary dependency cache")
set(VC_LTL_Root "$ENV{VC_LTL_Root}" CACHE PATH "Existing VC-LTL binary package; empty downloads the verified package")
foreach(dependency METAHOOK STEAMSDK GLEW GLFW)
    set(${dependency}_SOURCE_PATH "$ENV{${dependency}_SOURCE_PATH}" CACHE PATH "${dependency} source tree; empty fetches the pinned version")
endforeach()
set(CAPSTONE_INCLUDE_DIRS "$ENV{CAPSTONE_INCLUDE_DIRS}" CACHE STRING "External Capstone include directories; empty prefers the SDK's fork, then the pinned commit")

function(steamscreenshots_require_files name source)
    foreach(required IN LISTS ARGN)
        if(NOT EXISTS "${source}/${required}" OR IS_DIRECTORY "${source}/${required}")
            message(FATAL_ERROR "${name} is missing ${required}: ${source}")
        endif()
    endforeach()
endfunction()

# Populate only; GLEW and GLFW are configured separately with EXCLUDE_FROM_ALL.
function(steamscreenshots_fetch_source name url commit out_var)
    include(FetchContent)
    FetchContent_Declare(${name}
        GIT_REPOSITORY "${url}" GIT_TAG "${commit}"
        GIT_SUBMODULES "" GIT_SUBMODULES_RECURSE FALSE
        SOURCE_SUBDIR _steamscreenshots_source_only)
    FetchContent_MakeAvailable(${name})
    set(${out_var} "${${name}_SOURCE_DIR}" PARENT_SCOPE)
endfunction()

function(steamscreenshots_prepare_dependencies)
    set(METAHOOK_files include/metahook.h include/HLSDK/common/interface.cpp
        include/HLSDK/common/parsemsg.cpp include/HLSDK/common/cvardef.h include/Interface/IPlugins.h LICENSE)
    set(STEAMSDK_files steam/steam_api.h lib/steam_api.lib bin/steam_api.dll STEAM-SDK-NOTICE.md)
    set(GLEW_files CMakeLists.txt include/GL/glew.h src/glew.c LICENSE.txt)
    set(GLFW_files CMakeLists.txt include/GLFW/glfw3.h)
    set(vcltl_files "VC-LTL helper for cmake.cmake" config/config.cmake Readme.md
        TargetPlatform/6.0.6000.0/lib/Win32/libucrt.lib)
    set(dependencies METAHOOK STEAMSDK GLEW)
    if(BUILD_TESTING)
        list(APPEND dependencies GLFW)
    endif()

    # Explicit external trees are read-only inputs; reject invalid paths before downloading.
    foreach(dependency IN LISTS dependencies)
        if(${dependency}_SOURCE_PATH)
            get_filename_component(${dependency}_SOURCE_PATH "${${dependency}_SOURCE_PATH}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
            steamscreenshots_require_files("${dependency}_SOURCE_PATH" "${${dependency}_SOURCE_PATH}" ${${dependency}_files})
        endif()
    endforeach()
    if(VC_LTL_Root)
        get_filename_component(VC_LTL_Root "${VC_LTL_Root}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
        steamscreenshots_require_files(VC_LTL_Root "${VC_LTL_Root}" ${vcltl_files})
    endif()

    set(capstone_includes)
    set(capstone_header_found FALSE)
    foreach(directory IN LISTS CAPSTONE_INCLUDE_DIRS)
        get_filename_component(directory "${directory}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
        if(NOT IS_DIRECTORY "${directory}")
            message(FATAL_ERROR "CAPSTONE_INCLUDE_DIRS directory does not exist: ${directory}")
        endif()
        if(EXISTS "${directory}/capstone.h")
            set(capstone_header_found TRUE)
        elseif(EXISTS "${directory}/capstone/capstone.h")
            string(APPEND directory "/capstone")
            set(capstone_header_found TRUE)
        endif()
        list(APPEND capstone_includes "${directory}")
    endforeach()
    if(CAPSTONE_INCLUDE_DIRS AND NOT capstone_header_found)
        message(FATAL_ERROR "CAPSTONE_INCLUDE_DIRS must provide capstone.h or capstone/capstone.h")
    endif()
    if(DEFINED CAPSTONE_LIBRARY_DIRS)
        message(STATUS "CAPSTONE_LIBRARY_DIRS is ignored: SteamScreenshots uses headers through the MetaHook API and does not link Capstone.")
    endif()

    set(METAHOOK_url https://github.com/MetaHookSv/MetaHook)
    set(METAHOOK_commit 4d23b6fecd79dc949aabc2e145480cd1328d4a35)
    set(STEAMSDK_url https://github.com/MetaHookSv/SteamSDK)
    set(STEAMSDK_commit 3c1abaf6277f9f99fd16ef40557d6852820b848f)
    set(GLEW_url https://github.com/hzqst/glew-cmake)
    set(GLEW_commit 56ed32d4a929f993f0e6b7f905af9be4d38fda04)
    set(GLFW_url https://github.com/glfw/glfw.git)
    set(GLFW_commit 7b6aead9fb88b3623e3b3725ebb42670cbe4c579)
    foreach(dependency IN LISTS dependencies)
        if(NOT ${dependency}_SOURCE_PATH)
            string(TOLOWER "${dependency}" name)
            steamscreenshots_fetch_source(steamscreenshots_${name} "${${dependency}_url}" "${${dependency}_commit}" ${dependency}_SOURCE_PATH)
        endif()
        steamscreenshots_require_files("${dependency}_SOURCE_PATH" "${${dependency}_SOURCE_PATH}" ${${dependency}_files})
        set(${dependency}_SOURCE_PATH "${${dependency}_SOURCE_PATH}" PARENT_SCOPE)
        message(STATUS "${dependency}_SOURCE_PATH: ${${dependency}_SOURCE_PATH}")
    endforeach()

    if(NOT CAPSTONE_INCLUDE_DIRS)
        set(host_capstone "${METAHOOK_SOURCE_PATH}/thirdparty/capstone_fork/include/capstone")
        if(EXISTS "${host_capstone}/capstone.h")
            set(capstone_includes "${host_capstone}")
        else()
            steamscreenshots_fetch_source(steamscreenshots_capstone
                "https://github.com/hzqst/capstone"
                "e81e390f621ee59d14f70e16fe065dd00f78ee71" capstone_source)
            set(capstone_includes "${capstone_source}/include/capstone")
        endif()
    endif()
    set(STEAMSCREENSHOTS_CAPSTONE_INCLUDE_DIRS "${capstone_includes}" PARENT_SCOPE)
    message(STATUS "Capstone headers: ${capstone_includes}")

    if(NOT VC_LTL_Root)
        set(VC_LTL_Root "${STEAMSCREENSHOTS_DEPENDENCY_CACHE_DIR}/VC-LTL-5.3.1")
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VCLTL.cmake")
        steamscreenshots_prepare_vcltl()
    endif()
    steamscreenshots_require_files(VC_LTL_Root "${VC_LTL_Root}" ${vcltl_files})
    set(VC_LTL_Root "${VC_LTL_Root}" PARENT_SCOPE)

    # Directory-scoped: UtilHTTPClient_SteamAPI defines its own SteamSDK::SteamAPI with a
    # different include root, and both may share one aggregating parent build.
    add_library(SteamSDK::SteamAPI SHARED IMPORTED)
    set_target_properties(SteamSDK::SteamAPI PROPERTIES
        IMPORTED_IMPLIB "${STEAMSDK_SOURCE_PATH}/lib/steam_api.lib"
        IMPORTED_LOCATION "${STEAMSDK_SOURCE_PATH}/bin/steam_api.dll"
        INTERFACE_INCLUDE_DIRECTORIES "${STEAMSDK_SOURCE_PATH}/steam")
endfunction()
